/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;

public class FrmControlEstadia extends javax.swing.JFrame {

  //variable para recordar qué reserva buscamos
    private Reserva reservaActual = null;
    
    public FrmControlEstadia() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Check-in / Check-out");
        
        //bloqueo inicial de cajas para que nadie escriba donde no debe
        txtHuesped.setEditable(false);
        txtHabitacion.setEditable(false);
        txtEstado.setEditable(false);
        
        btnCheckIn.setEnabled(false);
        btnCheckOut.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdReserva = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHuesped = new javax.swing.JTextField();
        txtHabitacion = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMontoHospedaje = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMontoServicios = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código Reserva (R-XXX):");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("BUSCADOR:");

        jLabel3.setText("INFORMACIÓN:");

        jLabel4.setText("Huésped:");

        jLabel5.setText("Habitación:");

        jLabel6.setText("Estado Reserva:");

        txtHuesped.setEditable(false);

        txtHabitacion.setEditable(false);

        txtEstado.setEditable(false);

        btnCheckIn.setText("REGISTRAR INGRESO (CHECK-IN)");
        btnCheckIn.setEnabled(false);
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckOut.setText("REGISTRAR SALIDA (CHECK-OUT)");
        btnCheckOut.setEnabled(false);
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel7.setText("HOSPEDAJE:");

        jLabel8.setText("Costo Hospedaje (S/.):");

        txtMontoHospedaje.setEditable(false);

        jLabel9.setText("EXTRAS:");

        jLabel10.setText("Costo Consumos (S/.):");

        txtMontoServicios.setEditable(false);

        jLabel11.setText("TOTAL:");

        jLabel12.setText("TOTAL A PAGAR (S/.):");
        jLabel12.setToolTipText("");

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnBuscar)
                                            .addComponent(txtHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(txtHabitacion))))
                                .addGap(176, 386, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCheckOut)
                                    .addComponent(btnCheckIn)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(42, 42, 42)
                                    .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel12))
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMontoHospedaje)
                                        .addComponent(txtMontoServicios)
                                        .addComponent(txtTotalPagar)))))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCheckIn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnCheckOut)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMontoHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMontoServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     String id = txtIdReserva.getText().trim();
        
        //buscamos la reserva
        reservaActual = FrmGenerarReserva.controladorReserva.buscarPorId(id);
        
        if (reservaActual != null) {
            //Mostrar dato
            txtHuesped.setText(reservaActual.getHuesped().getNombre() + " " + reservaActual.getHuesped().getApellido());
            txtHabitacion.setText("Hab. " + reservaActual.getHabitacion().getNumero());
            txtEstado.setText(reservaActual.getEstado());
            

            txtMontoHospedaje.setText(String.valueOf(reservaActual.getMontoTotal()));
            txtMontoServicios.setText(String.valueOf(reservaActual.getMontoServicios()));
            txtTotalPagar.setText(String.valueOf(reservaActual.getMontoFinal()));
            

            String estado = reservaActual.getEstado();
            
            if (estado.equals("Pendiente")) {
                btnCheckIn.setEnabled(true);
                btnCheckOut.setEnabled(false);
            } else if (estado.equals("En Curso")) {
                btnCheckIn.setEnabled(false);
                btnCheckOut.setEnabled(true); 
            } else {
                btnCheckIn.setEnabled(false);
                btnCheckOut.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Esta reserva ya fue finalizada/pagada.");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Reserva no encontrada.");
            limpiar();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
       if (reservaActual == null) return;

        Habitacion hab = reservaActual.getHabitacion();
        
        if (!hab.getEstado().equals("Disponible") && !hab.getEstado().equals("Limpia")) {
             JOptionPane.showMessageDialog(this, "Error: La habitación " + hab.getNumero() + " aún no está lista (Estado: " + hab.getEstado() + ").");
             return;
        }


        reservaActual.setEstado("En Curso"); 
        hab.setEstado("Ocupado");           
        
        JOptionPane.showMessageDialog(this, "Check-in realizado.\nHabitación " + hab.getNumero() + " marcada como OCUPADA.");
        limpiar();
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
       if (reservaActual == null) return;
        

        String factura = "--- COMPROBANTE DE PAGO ---\n" +
                         "Cliente: " + txtHuesped.getText() + "\n" +
                         "---------------------------\n" +
                         "Alojamiento:   S/. " + txtMontoHospedaje.getText() + "\n" +
                         "Consumos Extra: S/. " + txtMontoServicios.getText() + "\n" +
                         "---------------------------\n" +
                         "TOTAL PAGADO:  S/. " + txtTotalPagar.getText() + "\n\n" +
                         "¿Confirmar pago y salida?";


        int confirm = JOptionPane.showConfirmDialog(this, factura, "Confirmar Check-out", JOptionPane.YES_NO_OPTION);
        
        if (confirm == 0) { 
            

            reservaActual.setEstado("Finalizada");
            reservaActual.getHabitacion().setEstado("En Limpieza");
            
            JOptionPane.showMessageDialog(this, "Pago registrado con éxito.\nLa habitación pasó a estado: EN LIMPIEZA.");
            limpiar();
        }
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmControlEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmControlEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmControlEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmControlEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmControlEstadia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtHabitacion;
    private javax.swing.JTextField txtHuesped;
    private javax.swing.JTextField txtIdReserva;
    private javax.swing.JTextField txtMontoHospedaje;
    private javax.swing.JTextField txtMontoServicios;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
private void limpiar() {
        txtIdReserva.setText("");
        txtHuesped.setText("");
        txtHabitacion.setText("");
        txtEstado.setText("");
        

        txtMontoHospedaje.setText("");
        txtMontoServicios.setText("");
        txtTotalPagar.setText("");
        
        btnCheckIn.setEnabled(false);
        btnCheckOut.setEnabled(false);
        reservaActual = null;
        txtIdReserva.requestFocus();
    }
}
