/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.*; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmGestionHabitaciones extends javax.swing.JFrame {

    public static ArregloHabitaciones controlador = new ArregloHabitaciones();
    

    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    public FrmGestionHabitaciones() {
        initComponents();
        configurarTabla();
        listar();
        this.setLocationRelativeTo(null); //esto centra ventana xd
        this.setResizable(false);
        this.setTitle("Gestión de Habitaciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cboTipo = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jb = new javax.swing.JScrollPane();
        tblHabitaciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblStockSimple = new javax.swing.JLabel();
        lblStockDoble = new javax.swing.JLabel();
        lblStockMatrimonial = new javax.swing.JLabel();
        lblStockSuite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número");

        jLabel2.setText("Tipo");

        jLabel3.setText("Capacidad");

        jLabel4.setText("Precio");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Matrimonial", "Suite" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tblHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHabitacionesMouseClicked(evt);
            }
        });
        jb.setViewportView(tblHabitaciones);

        lblStockSimple.setText("Simple:0");

        lblStockDoble.setText("Doble: 0");

        lblStockMatrimonial.setText("Matrimonial: 0");

        lblStockSuite.setText("Suite: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblStockSimple)
                .addGap(74, 74, 74)
                .addComponent(lblStockDoble)
                .addGap(47, 47, 47)
                .addComponent(lblStockMatrimonial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStockSuite)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockDoble)
                    .addComponent(lblStockMatrimonial)
                    .addComponent(lblStockSuite))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(26, 26, 26)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(40, 40, 40)
                        .addComponent(btnVolver)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumero)
                            .addComponent(txtCapacidad)
                            .addComponent(txtPrecio)
                            .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnVolver))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String numStr = txtNumero.getText().trim(); 
        String capStr = txtCapacidad.getText().trim();
        String preStr = txtPrecio.getText().trim();
        String tipo = cboTipo.getSelectedItem().toString();


        if (numStr.isEmpty() || capStr.isEmpty() || preStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }
        

        if (!esNumerico(numStr)) {
             JOptionPane.showMessageDialog(this, "El Número de Habitación debe ser un entero.");
             return;
        }
        if (!esNumerico(capStr) || !esNumerico(preStr)) {
            JOptionPane.showMessageDialog(this, "Capacidad y Precio deben ser números.");
            return;
        }


        int num = Integer.parseInt(numStr);

        if (controlador.buscar(num) != null) {
            JOptionPane.showMessageDialog(this, "El número de habitación " + num + " ya existe.");
            return;
        }


        int cap = Integer.parseInt(capStr);
        double pre = Double.parseDouble(preStr);
        
        Habitacion h = new Habitacion(num, tipo, cap, pre);
        controlador.adicionar(h);
        
        listar();
        limpiar();
        JOptionPane.showMessageDialog(this, "Habitación registrada.");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
     String numStr = txtNumero.getText().trim();
        
        if (!esNumerico(numStr)) {
             JOptionPane.showMessageDialog(this, "El numero no es válido.");
             return;
        }
        
        int num = Integer.parseInt(numStr); 
        Habitacion h = controlador.buscar(num); 
        
        if (h != null) {
            try {
                h.setTipo(cboTipo.getSelectedItem().toString());
                h.setCapacidad(Integer.parseInt(txtCapacidad.getText()));
                h.setPrecio(Double.parseDouble(txtPrecio.getText()));
                
                listar();
                limpiar();
                JOptionPane.showMessageDialog(this, "Habitación actualizada.");
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(this, "Error en los datos numéricos.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se encuentra la habitación.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     String numStr = txtNumero.getText();
        
        if (esNumerico(numStr)) {
             int num = Integer.parseInt(numStr);
             
             if (controlador.buscar(num) != null) {
                 int r = JOptionPane.showConfirmDialog(this, "¿Eliminar habitación " + num + "?");
                 if (r == 0) {
                     controlador.eliminar(num); 
                     listar();
                     limpiar();
                 }
             }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
     this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHabitacionesMouseClicked
    int fila = tblHabitaciones.getSelectedRow();
        if (fila != -1) {
            Habitacion h = controlador.obtener(fila);
            
            txtNumero.setText(String.valueOf(h.getNumero())); 
            
            txtCapacidad.setText(String.valueOf(h.getCapacidad()));
            txtPrecio.setText(String.valueOf(h.getPrecio()));
            cboTipo.setSelectedItem(h.getTipo());
            
            txtNumero.setEditable(false);
            btnGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_tblHabitacionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionHabitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jb;
    private javax.swing.JLabel lblStockDoble;
    private javax.swing.JLabel lblStockMatrimonial;
    private javax.swing.JLabel lblStockSimple;
    private javax.swing.JLabel lblStockSuite;
    private javax.swing.JTable tblHabitaciones;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void configurarTabla() {
        modeloTabla.addColumn("NUMERO");
        modeloTabla.addColumn("TIPO");
        modeloTabla.addColumn("CAPACIDAD");
        modeloTabla.addColumn("PRECIO");
        modeloTabla.addColumn("ESTADO");
        tblHabitaciones.setModel(modeloTabla);
    }


public void listar() {

        modeloTabla.setRowCount(0);
        

        for (int i = 0; i < controlador.tamano(); i++) {
            Habitacion h = controlador.obtener(i);
            Object[] fila = {
                h.getNumero(),
                h.getTipo(),
                h.getCapacidad(),
                h.getPrecio(),
                h.getEstado()
            };
            modeloTabla.addRow(fila);
        }
        

        actualizarStock(); 
    }


    private void limpiar() {
        txtNumero.setText("");
        txtCapacidad.setText("");
        txtPrecio.setText("");
        cboTipo.setSelectedIndex(0);
        
        txtNumero.setEditable(true); 
        txtNumero.requestFocus();
        btnGuardar.setEnabled(true);
        tblHabitaciones.clearSelection();
    }
    

    private boolean esNumerico(String texto) {
        try {
            Double.parseDouble(texto);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    private void actualizarStock() {

        int cSimple = controlador.contarPorTipo("Simple");
        int cDoble = controlador.contarPorTipo("Doble");
        int cMatri = controlador.contarPorTipo("Matrimonial");
        int cSuite = controlador.contarPorTipo("Suite");
        

        lblStockSimple.setText("Simples: " + cSimple);
        lblStockDoble.setText("Dobles: " + cDoble);
        lblStockMatrimonial.setText("Matrimoniales: " + cMatri);
        lblStockSuite.setText("Suites: " + cSuite);
    }
}
