/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {


    public static modelo.Empleado usuarioLogueado; 

    public FrmMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        aplicarPermisos();


        if (lblFondo.getIcon() != null) {
            

            javax.swing.ImageIcon iconoOriginal = (javax.swing.ImageIcon) lblFondo.getIcon();
            java.awt.Image imagenOriginal = iconoOriginal.getImage();

            int anchoDestino = lblFondo.getWidth();
            int altoDestino = lblFondo.getHeight();


            if (anchoDestino > 0 && altoDestino > 0) {
                

                java.awt.Image imagenEscalada = imagenOriginal.getScaledInstance(anchoDestino, altoDestino, java.awt.Image.SCALE_SMOOTH);


                lblFondo.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSalir = new javax.swing.JMenu();
        mnCerrarSesion = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        mnEmpleados = new javax.swing.JMenuItem();
        mnHabitaciones = new javax.swing.JMenuItem();
        mnHuespedes = new javax.swing.JMenuItem();
        mnServicios = new javax.swing.JMenuItem();
        Reservas = new javax.swing.JMenu();
        mnNuevaReserva = new javax.swing.JMenuItem();
        mnControlEstadia = new javax.swing.JMenuItem();
        mnConsumo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnReportes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmSalir.setText("Salir");
        btmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btmSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 132, 49));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SISTEMA-HOTEL-GRUPO-5-30-11-2025.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -50, 1030, 220));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gemini_Generated_Image_9p1gqw9p1gqw9p1g (1).png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        mnSalir.setText("Archivo");

        mnCerrarSesion.setText("Cerrar sesión");
        mnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarSesionActionPerformed(evt);
            }
        });
        mnSalir.add(mnCerrarSesion);

        jMenuItem2.setText("Salir del Sistema");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnSalir.add(jMenuItem2);

        jMenuBar1.add(mnSalir);

        menuMantenimiento.setText("Mantenimiento");

        mnEmpleados.setText("Gestionar Empleados");
        mnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEmpleadosActionPerformed(evt);
            }
        });
        menuMantenimiento.add(mnEmpleados);

        mnHabitaciones.setText("Gestionar Habitaciones");
        mnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHabitacionesActionPerformed(evt);
            }
        });
        menuMantenimiento.add(mnHabitaciones);

        mnHuespedes.setText("Gestionar Huespedes");
        mnHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHuespedesActionPerformed(evt);
            }
        });
        menuMantenimiento.add(mnHuespedes);

        mnServicios.setText("Gestionar Servicios");
        mnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServiciosActionPerformed(evt);
            }
        });
        menuMantenimiento.add(mnServicios);

        jMenuBar1.add(menuMantenimiento);

        Reservas.setText("Reservas");

        mnNuevaReserva.setText("Nueva Reserva");
        mnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNuevaReservaActionPerformed(evt);
            }
        });
        Reservas.add(mnNuevaReserva);

        mnControlEstadia.setText("Check-in/Check-out");
        mnControlEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnControlEstadiaActionPerformed(evt);
            }
        });
        Reservas.add(mnControlEstadia);

        mnConsumo.setText("Registrar Consumo");
        mnConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsumoActionPerformed(evt);
            }
        });
        Reservas.add(mnConsumo);

        jMenuBar1.add(Reservas);

        jMenu1.setText("Reportes");

        mnReportes.setText("Ver Reportes");
        mnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReportesActionPerformed(evt);
            }
        });
        jMenu1.add(mnReportes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEmpleadosActionPerformed

        new FrmGestionEmpleados().setVisible(true);
    }//GEN-LAST:event_mnEmpleadosActionPerformed

    private void btmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalirActionPerformed
 int rpta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?");
    if (rpta == 0) {
        System.exit(0); 
    }
    }//GEN-LAST:event_btmSalirActionPerformed

    private void mnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHabitacionesActionPerformed
 // Abrimos la ventana de habitaciones
        new FrmGestionHabitaciones().setVisible(true);
    }//GEN-LAST:event_mnHabitacionesActionPerformed

    private void mnHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHuespedesActionPerformed
     new FrmGestionHuespedes().setVisible(true);
    }//GEN-LAST:event_mnHuespedesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       System.exit(0); // Esto mata todo el proceso de Java
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarSesionActionPerformed
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "¿Desea cerrar la sesión actual?");
        
        if (r == 0) { 
            

            usuarioLogueado = null;
            

            this.dispose();
            

            new FrmLogin().setVisible(true);
        }
    }//GEN-LAST:event_mnCerrarSesionActionPerformed

    private void mnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServiciosActionPerformed
       new FrmGestionServicios().setVisible(true);
    }//GEN-LAST:event_mnServiciosActionPerformed

    private void mnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNuevaReservaActionPerformed
    new FrmGenerarReserva().setVisible(true);
    }//GEN-LAST:event_mnNuevaReservaActionPerformed

    private void mnControlEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnControlEstadiaActionPerformed
       new FrmControlEstadia().setVisible(true);
       
    }//GEN-LAST:event_mnControlEstadiaActionPerformed

    private void mnConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsumoActionPerformed
        // Abre la ventana de consumos
        new FrmRegistroConsumo().setVisible(true);
    }//GEN-LAST:event_mnConsumoActionPerformed

    private void mnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReportesActionPerformed
        new FrmReportes().setVisible(true);
    }//GEN-LAST:event_mnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Reservas;
    private javax.swing.JButton btmSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenuItem mnCerrarSesion;
    private javax.swing.JMenuItem mnConsumo;
    private javax.swing.JMenuItem mnControlEstadia;
    private javax.swing.JMenuItem mnEmpleados;
    private javax.swing.JMenuItem mnHabitaciones;
    private javax.swing.JMenuItem mnHuespedes;
    private javax.swing.JMenuItem mnNuevaReserva;
    private javax.swing.JMenuItem mnReportes;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenuItem mnServicios;
    // End of variables declaration//GEN-END:variables
private void aplicarPermisos() {

        if (usuarioLogueado == null) return;

        String rol = usuarioLogueado.obtenerRol();


        if (rol.equals("Administrador")) {
            

            mnEmpleados.setEnabled(true);
            mnHabitaciones.setEnabled(true);
            mnServicios.setEnabled(true);
            

            if (mnReportes != null) mnReportes.setEnabled(true); 


            mnHuespedes.setEnabled(false);
            
            if (mnNuevaReserva != null) mnNuevaReserva.setEnabled(false);
            if (mnControlEstadia != null) mnControlEstadia.setEnabled(false);
            if (mnConsumo != null) mnConsumo.setEnabled(false);


        } else if (rol.equals("Recepcionista")) {
            

            mnEmpleados.setEnabled(false);
            mnHabitaciones.setEnabled(false);
            mnServicios.setEnabled(false);
            

            if (mnReportes != null) mnReportes.setEnabled(false); 

            mnHuespedes.setEnabled(true);
            
            if (mnNuevaReserva != null) mnNuevaReserva.setEnabled(true);
            if (mnControlEstadia != null) mnControlEstadia.setEnabled(true);
            if (mnConsumo != null) mnConsumo.setEnabled(true);
        }
    }
}

